---
stages:
- name: '---'
  request:
    headers:
      x-token: required
    json:
      state: required
    method: PATCH
    url: http://172.16.130.254:5000/api/v1/domain/{domain_uuid}
  response:
    status_code: 200
    strict: false
test_name: 保护域-更新保护域状态
