---
stages:
- name: 查询角色权限列表
  request:
    headers:
      x-token: required
    method: GET
    url: http://172.16.130.254:5000/api/v1/domain/{domain_uuid}/permission
  response:
    status_code: 200
    strict: false
test_name: 角色权限管理-查询角色权限列表-查询角色权限列表
