---
stages:
- name: 修改用户
  request:
    headers:
      x-token: required
    json:
      user_group_members: required
      user_group_name: required
      user_group_role: required
    method: PUT
    params:
      async_mode: optional
    url: http://172.16.130.254:5000/api/v1/domain/{domain_uuid}/user_group/{user_group_uuid}
  response:
    status_code: 200
    strict: false
test_name: 用户组管理-修改用户组-修改用户
