---
stages:
- name: 格式化虚拟磁盘或物理磁盘为数据卷
  request:
    headers:
      x-token: required
    method: POST
    params:
      type: optional
    url: http://172.16.130.254:5000/api/v1/domain/{domain_uuid}/volume
  response:
    status_code: 200
    strict: false
test_name: 数据卷-格式化虚拟磁盘或物理磁盘为数据卷-格式化虚拟磁盘或物理磁盘为数据卷
