---
stages:
- name: ¸üĞÂĞéÄâ´ÅÅÌ×´Ì¬
  request:
    headers:
      x-token: required
    json:
      state: required
    method: PATCH
    url: http://172.16.130.254:5000/api/v1/domain/{domain_uuid}/vdisk/{vdisk_id}
  response:
    status_code: 200
    strict: false
test_name: ĞéÄâ´ÅÅÌ-¸üĞÂĞéÄâ´ÅÅÌ×´Ì¬-¸üĞÂĞéÄâ´ÅÅÌ×´Ì¬
