---
stages:
- name: É¾³ıĞéÄâ´ÅÅÌ
  request:
    headers:
      x-token: required
    json:
      state: required
    method: DELETE
    url: http://172.16.130.254:5000/api/v1/domain/{domain_uuid}/vdisk/{vdisk_id}
  response:
    status_code: 200
    strict: false
test_name: ĞéÄâ´ÅÅÌ-É¾³ıĞéÄâ´ÅÅÌ-É¾³ıĞéÄâ´ÅÅÌ
