---
stages:
- name: ĞÂ½¨ĞéÄâ´ÅÅÌ
  request:
    headers:
      x-token: required
    method: POST
    url: http://172.16.130.254:5000/api/v1/domain/{domain_uuid}/diskpool/{pool_id}/vdisk
  response:
    status_code: 200
    strict: false
test_name: ĞéÄâ´ÅÅÌ-ĞÂ½¨ĞéÄâ´ÅÅÌ-ĞÂ½¨ĞéÄâ´ÅÅÌ
