---
stages:
- name: </b><br/>修改
  request:
    method: POST
    url: http://172.16.130.254:5000/api/v1/domain/{domain_uuid}/fc_port/{wwpn}
  response:
    status_code: 200
    strict: false
test_name: 服务管理-分布式块设备-FiberChannel-Fc端口管理-修改
