---
stages:
- name: 查询用户列表
  request:
    headers:
      x-token: required
    method: GET
    params:
      user_role: optional
    url: http://172.16.130.254:5000/api/v1/domain/{domain_uuid}/user
  response:
    status_code: 200
    strict: false
test_name: 用户管理-查询用户列表-查询用户列表
