---
stages:
- name: '---'
  request:
    headers:
      x-token: required
    method: POST
    url: http://172.16.130.254:5000/api/v1/service/service_manage/set_dns_ip
  response:
    status_code: 200
    strict: false
test_name: 服务管理-设置Dns的Ip地址
